### ISSUE TITLE
HU 02 Consultar información detallada de un Album

### ISSUE THREAD

**Issue by mvegaruniandes** [The-Software-Design-Company/tsdc-vynils-app#8]
## Descripción

Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él

## Wireframe

![Image](https://github.com/The-Software-Design-Company/tsdc-vynils-app/assets/123474270/df47806b-e8ad-455c-8448-bdd9b40a2bc9)

## Cristerios de aceptación

- Al hacer clic en un álbum desde el listado, se debe mostrar una pantalla con detalles específicos sobre ese álbum.
- La pantalla de detalle debe mostrar información detallada del álbum, incluyendo su nombre, portada, fecha de lanzamiento, descripción, género y compañía discográfica.
- La consulta de información detallada debe ser accesible incluso para usuarios visitantes sin necesidad de iniciar sesión.
- Debe ser fácil regresar desde la pantalla de detalle a la lista de coleccionistas.
- No se debe presentar información de otros álbumes.
- Listar las canciones asociadas al álbum.

## Mockup

![Image](https://github.com/The-Software-Design-Company/tsdc-vynils-app/assets/48004607/7f997614-0332-4d5b-b13a-361cf3353a14)

**Comment by zearkiatos** [comment]
Agregar listado de las canciones

**Comment by zearkiatos** [comment]
Agregar un boton de agregar track para el album
